In [1]:
# import libraies
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import sqlite3 
import seaborn as sns 
from pathlib import Path

In [2]:
# create the default path
BASE_PATH = Path.cwd()

In [3]:
# connect to the sql database 
conn = sqlite3.connect(BASE_PATH / "../database" / 'safety.db')
# import all the tables from the database 
operators_table = pd.read_sql_query("SELECT * FROM operators", conn)
print(operators_table.info())

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           60 non-null     int64
 1   employee_id  60 non-null     str
 2   first_name   60 non-null     str
 3   last_name    60 non-null     str
 4   email        60 non-null     str
 5   department   60 non-null     str
 6   position     60 non-null     str
 7   shift        60 non-null     str
 8   is_active    60 non-null     int64
 9   created_at   60 non-null     str
dtypes: int64(2), str(8)
memory usage: 11.3 KB
None

In [4]:
chemical_table = pd.read_sql_query("SELECT * FROM chemicals", conn)
print(chemical_table.info())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             20 non-null     int64
 1   chemical_name  20 non-null     str
 2   cas_number     20 non-null     str
 3   hazard_class   20 non-null     str
 4   created_at     20 non-null     str
dtypes: int64(1), str(4)
memory usage: 1.9 KB
None

In [5]:
reports_table = pd.read_sql_query("SELECT * FROM reports", conn)
print(reports_table.info())

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                3000 non-null   int64
 1   title             3000 non-null   str
 2   description       3000 non-null   str
 3   operator_id       3000 non-null   int64
 4   chemical_id       3000 non-null   int64
 5   incident_type_id  3000 non-null   int64
 6   severity          3000 non-null   str
 7   location          3000 non-null   str
 8   created_at        3000 non-null   str
dtypes: int64(4), str(5)
memory usage: 821.3 KB
None

In [6]:
incident_types = pd.read_sql_query("SELECT * FROM incident_types", conn)
print(incident_types.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           10 non-null     int64
 1   name         10 non-null     str
 2   description  10 non-null     str
dtypes: int64(1), str(2)
memory usage: 1.0 KB
None

In [7]:
def check_data(table_name, data):
    check_null = data.isnull().sum()
    check_duplicates = data.duplicated().sum()
    check_shape = data.shape
    check_columns = list(data)
    check_datatype = data.dtypes
    return{
        "Table" : table_name,
        "Null Counts" : check_null,
        "Duplicates Counts" : check_duplicates,
        "Shape" :  check_shape,
        "Columns" : check_columns,
        "Data Type" : check_datatype
    }

check_data("Reports Table", reports_table)

{'Table': 'Reports Table',
 'Null Counts': id                  0
 title               0
 description         0
 operator_id         0
 chemical_id         0
 incident_type_id    0
 severity            0
 location            0
 created_at          0
 dtype: int64,
 'Duplicates Counts': np.int64(0),
 'Shape': (3000, 9),
 'Columns': ['id',
  'title',
  'description',
  'operator_id',
  'chemical_id',
  'incident_type_id',
  'severity',
  'location',
  'created_at'],
 'Data Type': id                  int64
 title                 str
 description           str
 operator_id         int64
 chemical_id         int64
 incident_type_id    int64
 severity              str
 location              str
 created_at            str
 dtype: object}

In [8]:
check_data("Operators Table", operators_table)

{'Table': 'Operators Table',
 'Null Counts': id             0
 employee_id    0
 first_name     0
 last_name      0
 email          0
 department     0
 position       0
 shift          0
 is_active      0
 created_at     0
 dtype: int64,
 'Duplicates Counts': np.int64(0),
 'Shape': (60, 10),
 'Columns': ['id',
  'employee_id',
  'first_name',
  'last_name',
  'email',
  'department',
  'position',
  'shift',
  'is_active',
  'created_at'],
 'Data Type': id             int64
 employee_id      str
 first_name       str
 last_name        str
 email            str
 department       str
 position         str
 shift            str
 is_active      int64
 created_at       str
 dtype: object}

In [9]:
check_data("Chemical Table", chemical_table)

{'Table': 'Chemical Table',
 'Null Counts': id               0
 chemical_name    0
 cas_number       0
 hazard_class     0
 created_at       0
 dtype: int64,
 'Duplicates Counts': np.int64(0),
 'Shape': (20, 5),
 'Columns': ['id',
  'chemical_name',
  'cas_number',
  'hazard_class',
  'created_at'],
 'Data Type': id               int64
 chemical_name      str
 cas_number         str
 hazard_class       str
 created_at         str
 dtype: object}

In [10]:
check_data("Incident Type Table", incident_types)

{'Table': 'Incident Type Table',
 'Null Counts': id             0
 name           0
 description    0
 dtype: int64,
 'Duplicates Counts': np.int64(0),
 'Shape': (10, 3),
 'Columns': ['id', 'name', 'description'],
 'Data Type': id             int64
 name             str
 description      str
 dtype: object}

In [11]:
# join the incident type data with the reports data
reports_table.head()

,id,title,description,operator_id,chemical_id,incident_type_id,severity,location,created_at
0,1,Equipment Failure Report #1,Drive motor of the mixing vessel failed to mai...,48,1,4,HIGH,Catalyst Regeneration Unit,2026-10-13 15:40:04.433923
1,2,Operator Error Report #2,An incorrect adjustment during operation affec...,39,12,10,HIGH,Production Area A,2026-10-13 15:40:04.433943
2,3,Pressure Failure Report #3,The mixing vessel showed abnormal pressure rea...,47,10,2,CRITICAL,Catalyst Regeneration Unit,2026-10-13 15:40:04.433944
3,4,Fire Incident Report #4,Combustion was reported inside the enclosure o...,42,20,7,HIGH,Laboratory Section,2026-10-13 15:40:04.433944
4,5,Pressure Failure Report #5,A pressure deviation was detected in the react...,51,17,2,HIGH,Catalyst Regeneration Unit,2026-10-13 15:40:04.433945

In [12]:
incident_types.head()

,id,name,description
0,1,Temperature Excursion,Process temperature exceeded the designed oper...
1,2,Pressure Failure,Unexpected pressure increase or decrease durin...
2,3,Chemical Leak,Uncontrolled release of chemical substances.
3,4,Equipment Failure,Mechanical or electrical equipment malfunction.
4,5,Catalyst Degradation,Loss of catalyst activity affecting process pe...

In [13]:
joined_tables = pd.read_sql_query("""
SELECT i.name, i.description AS incident_description, r.title, r.description AS reports_description, r.operator_id, r.chemical_id, r.severity, r.location, r.created_at 
FROM incident_types as i
JOIN reports as r on i.id= r.incident_type_id
""", conn)
joined_tables.head()

,name,incident_description,title,reports_description,operator_id,chemical_id,severity,location,created_at
0,Equipment Failure,Mechanical or electrical equipment malfunction.,Equipment Failure Report #1,Drive motor of the mixing vessel failed to mai...,48,1,HIGH,Catalyst Regeneration Unit,2026-10-13 15:40:04.433923
1,Operator Error,Operational mistake during process handling.,Operator Error Report #2,An incorrect adjustment during operation affec...,39,12,HIGH,Production Area A,2026-10-13 15:40:04.433943
2,Pressure Failure,Unexpected pressure increase or decrease durin...,Pressure Failure Report #3,The mixing vessel showed abnormal pressure rea...,47,10,CRITICAL,Catalyst Regeneration Unit,2026-10-13 15:40:04.433944
3,Fire Incident,Combustion event caused by chemical or equipme...,Fire Incident Report #4,Combustion was reported inside the enclosure o...,42,20,HIGH,Laboratory Section,2026-10-13 15:40:04.433944
4,Pressure Failure,Unexpected pressure increase or decrease durin...,Pressure Failure Report #5,A pressure deviation was detected in the react...,51,17,HIGH,Catalyst Regeneration Unit,2026-10-13 15:40:04.433945

In [14]:
joined_tables['name'].value_counts()

name
Instrumentation Failure    324
Equipment Failure          323
Corrosion Failure          304
Fire Incident              300
Pressure Failure           299
Temperature Excursion      299
Contamination              299
Catalyst Degradation       293
Chemical Leak              289
Operator Error             270
Name: count, dtype: int64

In [15]:
joined_tables['incident_description'].value_counts()

incident_description
Failure of sensors or control instruments.                    324
Mechanical or electrical equipment malfunction.               323
Material degradation due to chemical corrosion.               304
Combustion event caused by chemical or equipment failure.     300
Unexpected pressure increase or decrease during operation.    299
Process temperature exceeded the designed operating range.    299
Unwanted material introduced into the process.                299
Loss of catalyst activity affecting process performance.      293
Uncontrolled release of chemical substances.                  289
Operational mistake during process handling.                  270
Name: count, dtype: int64

In [16]:
joined_tables['severity'].value_counts()

severity
CRITICAL    798
HIGH        782
MEDIUM      723
LOW         697
Name: count, dtype: int64

In [17]:
joined_tables['location'].value_counts()

location
Catalyst Regeneration Unit    443
Laboratory Section            435
Chemical Processing Bay       434
Production Area A             429
Storage Facility              428
Utilities Area                418
Refinery Unit 2               413
Name: count, dtype: int64

In [18]:
chemical_safety_data = joined_tables.copy()
chemical_safety_data.head()

,name,incident_description,title,reports_description,operator_id,chemical_id,severity,location,created_at
0,Equipment Failure,Mechanical or electrical equipment malfunction.,Equipment Failure Report #1,Drive motor of the mixing vessel failed to mai...,48,1,HIGH,Catalyst Regeneration Unit,2026-10-13 15:40:04.433923
1,Operator Error,Operational mistake during process handling.,Operator Error Report #2,An incorrect adjustment during operation affec...,39,12,HIGH,Production Area A,2026-10-13 15:40:04.433943
2,Pressure Failure,Unexpected pressure increase or decrease durin...,Pressure Failure Report #3,The mixing vessel showed abnormal pressure rea...,47,10,CRITICAL,Catalyst Regeneration Unit,2026-10-13 15:40:04.433944
3,Fire Incident,Combustion event caused by chemical or equipme...,Fire Incident Report #4,Combustion was reported inside the enclosure o...,42,20,HIGH,Laboratory Section,2026-10-13 15:40:04.433944
4,Pressure Failure,Unexpected pressure increase or decrease durin...,Pressure Failure Report #5,A pressure deviation was detected in the react...,51,17,HIGH,Catalyst Regeneration Unit,2026-10-13 15:40:04.433945

In [19]:
chemical_safety_data['reports_description'].nunique()

1301

In [20]:
# check if the reports has any incident 
for incident in chemical_safety_data['name'].unique():
    count = chemical_safety_data[chemical_safety_data['reports_description'].str.contains(incident, regex=False, case=False)].shape[0]
    print(incident , count)

Equipment Failure 0
Operator Error 0
Pressure Failure 0
Fire Incident 0
Instrumentation Failure 0
Chemical Leak 0
Temperature Excursion 0
Catalyst Degradation 0
Contamination 26
Corrosion Failure 0

In [39]:
pd.set_option('display.max_columns', None)
pd.set_option("display.max_rows", None)
pd.set_option('display.max_colwidth', None)

In [40]:
chemical_safety_data[chemical_safety_data['reports_description'].str.contains('contamination', case=False, regex=False)][['reports_description', 'name']]

,reports_description,name
251,Samples collected from the heat exchanger showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
293,Samples collected from the compressor showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
350,Samples collected from the heat exchanger showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
552,Samples collected from the catalyst chamber showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
610,Samples collected from the catalyst chamber showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
629,Samples collected from the pipeline showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
815,Samples collected from the mixing vessel showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
1027,Samples collected from the pipeline showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
1238,Samples collected from the pipeline showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
1242,Samples collected from the distillation column showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
1403,Samples collected from the pump system showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
1422,Samples collected from the heat exchanger showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
1500,Samples collected from the catalyst chamber showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
1836,Samples collected from the heat exchanger showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
1876,Samples collected from the compressor showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
1989,Samples collected from the distillation column showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
2025,Samples collected from the reactor showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
2106,Samples collected from the distillation column showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
2143,Samples collected from the heat exchanger showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
2303,Samples collected from the catalyst chamber showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
2493,Samples collected from the distillation column showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
2581,Samples collected from the pump system showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
2681,Samples collected from the storage tank showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
2697,Samples collected from the distillation column showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
2723,Samples collected from the pump system showed contamination indicators. The production line was stopped for line clearance checks.,Contamination
2862,Samples collected from the pump system showed contamination indicators. The production line was stopped for line clearance checks.,Contamination

In [22]:
chemical_safety_data['title'].nunique()

3000

In [23]:
chemical_safety_data['reports_description_word_counts'] = chemical_safety_data['reports_description'].str.split().str.len()

In [24]:
# get the minimum word count
chemical_safety_data['reports_description_word_counts'].min()

np.int64(11)

In [25]:
# get the maximun word count
chemical_safety_data['reports_description_word_counts'].max()

np.int64(25)

In [26]:
chemical_safety_data['reports_description'].sample(20)

1365    The distillation column showed signs of reduce...
1239    Vapor cloud was observed escaping from the rea...
2424    A release of process material was identified a...
1142    A wrong valve alignment on the reactor led to ...
1600    Abnormal noise and vibration were observed fro...
852     An unexpected rise in operating pressure was r...
2793    The pump system product stream was found to co...
2940    Measured values from the distillation column w...
1539    Protective coating on the reactor had deterior...
2726    The pipeline experienced a loss of pressure co...
1553    A combustion event occurred around the mixing ...
1500    Samples collected from the catalyst chamber sh...
1642    The mixing vessel was operated outside the app...
2712    A sudden thermal deviation was logged for the ...
2939    A missed step during operation of the compress...
1397    Abnormal noise and vibration were observed fro...
87      An unexpected heat buildup was observed in the...
1787    An unexpected rise in operating pressure was r...
2161    Pressure regulation failed momentarily in the ...
631     Quality control flagged off-spec results for p...
Name: reports_description, dtype: str

In [27]:
import os
os.makedirs("../data", exist_ok=True)
chemical_safety_data.to_csv("../data/chemical_safety_analyser_data.csv", index=False)

In [41]:
analysis_data = pd.DataFrame({
    "text" : chemical_safety_data['reports_description'],
    "target" : chemical_safety_data['name']
})
analysis_data.sample(20)

,text,target
1993,Integrity assessment of the pump system revealed localized corrosion near weld joints and connections.,Corrosion Failure
2469,The catalyst chamber failed to transmit correct data to the control system. Loop checking revealed faulty transmitter wiring.,Instrumentation Failure
2138,Laboratory tests showed elevated impurity levels in samples taken from the compressor. Cleaning verification was initiated.,Contamination
1031,The heat exchanger showed signs of reduced catalytic activity after several cycles. Product purity trended below target.,Catalyst Degradation
1013,Selectivity declined during operation in the mixing vessel. Process data showed increasing byproduct formation.,Catalyst Degradation
791,Operators inadvertently bypassed a critical interlock on the compressor. The bypass was removed and controls were verified.,Operator Error
2909,A sudden thermal deviation was logged for the reactor. The unit reached 179°C and remained above normal limits for several minutes.,Temperature Excursion
1564,Drive motor of the heat exchanger failed to maintain rotation. The system shut down automatically to prevent further damage.,Equipment Failure
2046,Personnel observed ignition near the seal of the storage tank. The area was evacuated and fire suppression systems were activated.,Fire Incident
2030,Abnormal noise and vibration were observed from the mixing vessel before it ceased operation. The unit was locked out for detailed inspection.,Equipment Failure
1435,Yield loss was observed during operation of the catalyst chamber. Laboratory analysis confirmed reduced catalyst effectiveness.,Catalyst Degradation
573,The distillation column triggered false alarms due to unstable measurement output. The sensor head was cleaned and tested.,Instrumentation Failure
449,A combustion event occurred around the storage tank. Personnel responded immediately and performed safety checks after the incident.,Fire Incident
331,Personnel observed ignition near the seal of the heat exchanger. The area was evacuated and fire suppression systems were activated.,Fire Incident
1557,Conversion rate dropped steadily while using the distillation column. Operators noted that longer residence time was needed to meet specifications.,Catalyst Degradation
426,Abnormal noise and vibration were observed from the pump system before it ceased operation. The unit was locked out for detailed inspection.,Equipment Failure
838,Operators noticed deviation between redundant instruments monitoring the storage tank. One channel was found to be faulty.,Instrumentation Failure
233,Vapor cloud was observed escaping from the heat exchanger. Operators shut off supply and initiated ventilation of the affected zone.,Chemical Leak
1809,The compressor was charged with incorrect material quantity due to misinterpretation of the batch sheet.,Operator Error
2182,A small fire broke out in the vicinity of the storage tank. Operators used portable extinguishers to prevent escalation.,Fire Incident

In [46]:
# the preprocessong step 
raw_analysis_data = analysis_data.copy()
raw_analysis_data.shape

(3000, 2)

In [ ]:
analysis_data = pd.DataFrame({
    "text" : chemical_safety_data['reports_description'],
    "target" : chemical_safety_data['name']
})
analysis_data.sample(20)

,text,target
1993,Integrity assessment of the pump system revealed localized corrosion near weld joints and connections.,Corrosion Failure
2469,The catalyst chamber failed to transmit correct data to the control system. Loop checking revealed faulty transmitter wiring.,Instrumentation Failure
2138,Laboratory tests showed elevated impurity levels in samples taken from the compressor. Cleaning verification was initiated.,Contamination
1031,The heat exchanger showed signs of reduced catalytic activity after several cycles. Product purity trended below target.,Catalyst Degradation
1013,Selectivity declined during operation in the mixing vessel. Process data showed increasing byproduct formation.,Catalyst Degradation
791,Operators inadvertently bypassed a critical interlock on the compressor. The bypass was removed and controls were verified.,Operator Error
2909,A sudden thermal deviation was logged for the reactor. The unit reached 179°C and remained above normal limits for several minutes.,Temperature Excursion
1564,Drive motor of the heat exchanger failed to maintain rotation. The system shut down automatically to prevent further damage.,Equipment Failure
2046,Personnel observed ignition near the seal of the storage tank. The area was evacuated and fire suppression systems were activated.,Fire Incident
2030,Abnormal noise and vibration were observed from the mixing vessel before it ceased operation. The unit was locked out for detailed inspection.,Equipment Failure
1435,Yield loss was observed during operation of the catalyst chamber. Laboratory analysis confirmed reduced catalyst effectiveness.,Catalyst Degradation
573,The distillation column triggered false alarms due to unstable measurement output. The sensor head was cleaned and tested.,Instrumentation Failure
449,A combustion event occurred around the storage tank. Personnel responded immediately and performed safety checks after the incident.,Fire Incident
331,Personnel observed ignition near the seal of the heat exchanger. The area was evacuated and fire suppression systems were activated.,Fire Incident
1557,Conversion rate dropped steadily while using the distillation column. Operators noted that longer residence time was needed to meet specifications.,Catalyst Degradation
426,Abnormal noise and vibration were observed from the pump system before it ceased operation. The unit was locked out for detailed inspection.,Equipment Failure
838,Operators noticed deviation between redundant instruments monitoring the storage tank. One channel was found to be faulty.,Instrumentation Failure
233,Vapor cloud was observed escaping from the heat exchanger. Operators shut off supply and initiated ventilation of the affected zone.,Chemical Leak
1809,The compressor was charged with incorrect material quantity due to misinterpretation of the batch sheet.,Operator Error
2182,A small fire broke out in the vicinity of the storage tank. Operators used portable extinguishers to prevent escalation.,Fire Incident

In [56]:
# clean the data for the analysis
analysis_data.to_csv("../data/analysed_data.csv", index=False)
raw_analysis_data = analysis_data.copy()

import spacy 
nlp = spacy.load('en_core_web_sm')
one_sentence = nlp("The catalyst chamber failed to transmit correct data to the control system. Loop checking revealed faulty transmitter wiring.")
for token in one_sentence:
    print(token.text, "-----" ,token.lemma_)

The ----- the
catalyst ----- catalyst
chamber ----- chamber
failed ----- fail
to ----- to
transmit ----- transmit
correct ----- correct
data ----- datum
to ----- to
the ----- the
control ----- control
system ----- system
. ----- .
Loop ----- Loop
checking ----- checking
revealed ----- reveal
faulty ----- faulty
transmitter ----- transmitter
wiring ----- wiring
. ----- .

In [60]:
# check for stop words and puntuation 
for words in one_sentence:
    print(words.text, "------", "Is Puntuation", "------", words.is_punct, "------", "StopWords", "-------", words.is_stop)

The ------ Is Puntuation ------ False ------ StopWords ------- True
catalyst ------ Is Puntuation ------ False ------ StopWords ------- False
chamber ------ Is Puntuation ------ False ------ StopWords ------- False
failed ------ Is Puntuation ------ False ------ StopWords ------- False
to ------ Is Puntuation ------ False ------ StopWords ------- True
transmit ------ Is Puntuation ------ False ------ StopWords ------- False
correct ------ Is Puntuation ------ False ------ StopWords ------- False
data ------ Is Puntuation ------ False ------ StopWords ------- False
to ------ Is Puntuation ------ False ------ StopWords ------- True
the ------ Is Puntuation ------ False ------ StopWords ------- True
control ------ Is Puntuation ------ False ------ StopWords ------- False
system ------ Is Puntuation ------ False ------ StopWords ------- False
. ------ Is Puntuation ------ True ------ StopWords ------- False
Loop ------ Is Puntuation ------ False ------ StopWords ------- False
checking ------ Is Puntuation ------ False ------ StopWords ------- False
revealed ------ Is Puntuation ------ False ------ StopWords ------- False
faulty ------ Is Puntuation ------ False ------ StopWords ------- False
transmitter ------ Is Puntuation ------ False ------ StopWords ------- False
wiring ------ Is Puntuation ------ False ------ StopWords ------- False
. ------ Is Puntuation ------ True ------ StopWords ------- False

In [62]:
second_sentence = nlp("A sudden thermal deviation was logged for the reactor. The unit reached 179°C and remained above normal limits for several minutes.")

for letters in second_sentence:
    print(letters.text, "----->", letters.lemma_)

A -----> a
sudden -----> sudden
thermal -----> thermal
deviation -----> deviation
was -----> be
logged -----> log
for -----> for
the -----> the
reactor -----> reactor
. -----> .
The -----> the
unit -----> unit
reached -----> reach
179 -----> 179
° -----> °
C -----> c
and -----> and
remained -----> remain
above -----> above
normal -----> normal
limits -----> limit
for -----> for
several -----> several
minutes -----> minute
. -----> .

In [86]:
# create a function to clean the text 
def clean_description(text: str) -> str:
    # replace all C with celsius
    text = text.replace("°C", ' celsius').replace("° C", ' celsius')
    sentence = nlp(text)
    # convert to lowercase 
    cleaned_tokens = []

    # remove puntuations and convet to lowercase
    for token in sentence:
        if token.is_stop or token.is_punct or token.is_space:
            continue
        
        lemma = token.lemma_.lower()
        if lemma == "datum":
            lemma = "data"
        if lemma in ['°', 'c']:
            lemma = 'celsius'
        
        cleaned_tokens.append(lemma)
    return " ".join(cleaned_tokens)

original_senetence = raw_analysis_data['text'].iloc[2909]
processed_sentence = clean_description(original_senetence)

print("Cleaned Sentence", ":", original_senetence)
print("Processed Sentence", ":", processed_sentence)

Cleaned Sentence : A sudden thermal deviation was logged for the reactor. The unit reached 179°C and remained above normal limits for several minutes.
Processed Sentence : sudden thermal deviation log reactor unit reach 179 celsius remain normal limit minute

In [91]:
# now append this function to the raw data
raw_analysis_data['cleaned_text'] = raw_analysis_data['text'].apply(clean_description)

In [93]:
raw_analysis_data.sample(20)

,text,target,cleaned_text
456,A combustion event occurred around the reactor. Personnel responded immediately and performed safety checks after the incident.,Fire Incident,combustion event occur reactor personnel respond immediately perform safety check incident
2971,Burning odor and visible smoke were reported around the compressor. Investigation confirmed combustion of leaked material.,Fire Incident,burn odor visible smoke report compressor investigation confirm combustion leak material
344,A wrong valve alignment on the mixing vessel led to abnormal process behavior. The alignment was corrected after discovery.,Operator Error,wrong valve alignment mix vessel lead abnormal process behavior alignment correct discovery
670,Extended use of the pipeline resulted in lower than expected yield. Activity testing suggested diminished catalyst performance.,Catalyst Degradation,extended use pipeline result low expect yield activity testing suggest diminished catalyst performance
2,The mixing vessel showed abnormal pressure readings during operation. The control team responded after pressure levels exceeded normal operating conditions.,Pressure Failure,mix vessel show abnormal pressure reading operation control team respond pressure level exceed normal operating condition
2999,The mixing vessel surface was found to be rough and deteriorated after exposure to aggressive process environment.,Corrosion Failure,mix vessel surface find rough deteriorate exposure aggressive process environment
789,Unplanned discharge was noted during routine inspection of the reactor. Spill control equipment was deployed to limit spread.,Chemical Leak,unplanned discharge note routine inspection reactor spill control equipment deploy limit spread
2848,"Pressure buildup was observed in the pipeline, with gauges indicating 15 bar. The relief system was inspected for proper function.",Pressure Failure,pressure buildup observe pipeline gauge indicate 15 bar relief system inspect proper function
1363,The compressor stopped functioning during production. Inspection revealed that normal operation could not continue and maintenance support was required.,Equipment Failure,compressor stop function production inspection reveal normal operation continue maintenance support require
448,The reactor experienced a loss of pressure containment. Readings reached 11 bar and fluctuated before stabilizing.,Pressure Failure,reactor experience loss pressure containment reading reach 11 bar fluctuate stabilize
179,Fluid accumulation was found on the ground near the mixing vessel. The source was traced to a small opening and containment measures were applied.,Chemical Leak,fluid accumulation find ground near mix vessel source trace small opening containment measure apply
316,Routine turnaround inspection found the pump system had developed corrosion-induced holes requiring immediate repair.,Corrosion Failure,routine turnaround inspection find pump system develop corrosion induce hole require immediate repair
2119,Delayed response to an alarm on the mixing vessel prolonged the off-normal condition. Response time was discussed in the safety meeting.,Operator Error,delay response alarm mix vessel prolong normal condition response time discuss safety meeting
1118,Sparks were observed from the compressor which led to ignition of nearby residues. The event was controlled without spread.,Fire Incident,spark observe compressor lead ignition nearby residue event control spread
1545,Leak paths were discovered in the distillation column body due to advanced material degradation over time.,Corrosion Failure,leak path discover distillation column body advanced material degradation time
2452,The mixing vessel became unresponsive to control commands. Operators switched to standby unit while troubleshooting the failure.,Equipment Failure,mix vessel unresponsive control command operator switch standby unit troubleshoot failure
1768,A fire alarm was triggered near the pump system. Response team confirmed localized combustion and secured the perimeter.,Fire Incident,fire alarm trigger near pump system response team confirm localize combustion secure perimeter
277,A small fire broke out in the vicinity of the mixing vessel. Operators used portable extinguishers to prevent escalation.,Fire Incident,small fire break vicinity mix vessel operator portable extinguisher prevent escalation
1397,Abnormal noise and vibration were observed from the heat exchanger before it ceased operation. The unit was locked out for detailed inspection.,Equipment Failure,abnormal noise vibration observe heat exchanger cease operation unit lock detailed inspection
2281,Reaction kinetics appeared slower than baseline in the heat exchanger. Evaluation indicated loss of active sites.,Catalyst Degradation,reaction kinetic appear slow baseline heat exchanger evaluation indicate loss active site

In [95]:
# train the data now 
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer